=== sergiorodriguesml/garantia_safra/xml_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="nis" type="xs:string"/>
	<xs:element name="nome" type="xs:string"/>
	<xs:element name="valor" type="xs:string"/>
	<xs:element name="beneficiario">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nis"/>
				<xs:element ref="nome"/>
				<xs:element ref="valor"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="beneficiarios">
		<xs:complexType>
			<xs:element ref="beneficiario" minOccurs="1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="municipio">
		<xs:complexType>
			<xs:element ref="nome"/>
			<xs:element ref="beneficiarios" maxOccurs="1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="estado">
		<xs:complexType>
			<xs:element ref="municipio" minOccurs="1"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GarantiaSafra">
		<xs:complexType>
			<xs:element ref="estado" minOccurs="1"/>
		</xs:complexType>
	</xs:element>
		<xs:element name="root">
		<xs:complexType>
			<xs:element ref="GarantiaSafra" minOccurs="1"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sergiorodriguesml/garantia_safra/xml_model.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="xml_Schema.xsd">
	<GarantiaSafra registro="201301">
			<estado sigla="AL">
				<municipio cod="2713">
					<nome>BATALHA</nome>
					<beneficiarios>
						<beneficiario>
							<nis>20635826733</nis>
							<nome>ADELMO DOS SANTOS DA SILVA</nome>
							<valor>135,00</valor>
						</beneficiario>
						<beneficiario>
							<nis>16161064953</nis>
							<nome>ADELSON DE OLIVEIRA</nome>
							<valor>135,00</valor>
						</beneficiario>
					</beneficiarios>
				</municipio>
			<estado>
	</GarantiaSafra>
</root>
